package fr.army.stelyteam.utils;

public enum TemporaryActionNames {
    REMOVE_MEMBER,
    REMOVE_ALLIANCE,
    EDIT_OWNER,
    CREATE_TEAM,
    BUY_TEAM_BANK,
    EDIT_NAME,
    EDIT_PREFIX,
    DELETE_TEAM,
    IMPROV_LVL_MEMBERS,
    IMPROV_LVL_STORAGE,
    LEAVE_TEAM,
    ADD_ALLIANCE,
    ADD_MEMBER,
    CREATE_HOME,
    DELETE_HOME,
    CLICK_REMOVE_MEMBER
}