# Connection à la base de donnée
sql:
  host: "localhost"
  database: "bungeecord_StelyTeam"
  user: "username"
  password: "password"
  port: 3306


# Timeout des conversations (message demandant une information aux joueurs lors de la création de team par exemple)
conversationTimeout: 60

# Mots permettant d'annuler une conversation (message demandant une information aux joueurs lors de la création de team par exemple)
conversationCancelWords:
  - "cancel"
  - "annuler"
  - "stop"
  - "quit"


# Permet d'ouvrir le menu de la team après après la création de la team
openTeamAfterCreate: true

# Nombre maximum de caracteres dans les noms de team (les couleurs ne sont pas prises en compte dans la limite)
teamNameMaxLength: 12
teamPrefixMaxLength: 12

# Argent maximal d'une team
teamMaxMoney: 1000000.0

# Nombre de membres maximum dans une team
teamMaxMembers: 10

# Prix des différentes actions
prices:
  createTeam: 10000.0
  editTeamId: 2000.0
  editTeamPrefix: 3000.0
  buyTeamBank: 500000.0
  upgrade:
    teamPlaces:
      level1: 25000.0
      level2: 50000.0
      level3: 100000.0
      level4: 150000.0
      level5: 250000.0
    teamStorages:
      level1: 10000.0
      level2: 25000.0
      level3: 50000.0
      level4: 80000.0
      level5: 100000.0


# Item à la place des cases vide
emptyCase: LIGHT_BLUE_STAINED_GLASS_PANE

# Item en cas de permission insuffisante
noPermission:
  itemName: "§cPermission insuffisante"
  itemType: RED_STAINED_GLASS_PANE
  lore: 
    - "§cPermission insuffisante"


# Item si le compte de la team n'a pas encore été débloquée
teamBankNotUnlock:
  itemName: "§c§nCompte non débloqué"
  itemType: EMERALD
  lore: 
    - "§cDébloquer le compte de"
    - "§cla team pour pouvoir"
    - "§cy avoir accès"

# Item si l'un des stockage de la team n'a pas encore été débloqué
storageNotUnlock:
  itemName: "§c§nStockage non débloqué"
  itemType: ENDER_CHEST

# Préfixe à gauche du rang, affiché dans le menu de la gestion des membres de la team et dans la liste des membres
prefixRankLore: "§r§e>> "

# Description des teams dans la liste des alliances
teamAllianceLore:
  - "§aGérant de la team : §e%OWNER%"
  - "§aNom : §e%NAME%"
  - "§aPréfixe : §r%PREFIX%"
  - "§aNombre de membre : §e%MEMBER_COUNT% sur %MAX_MEMBERS%"
  - "§aMembre(s) : §e%MEMBERS%"
  - "§aAllié depuis le §e%DATE%"  


# Titre des menus et leur nombre de slots
# Le nombre de slots peut être augmenté en fonction du tombre d'item dans le menu *
# * Respecter le nombre de slots en fonction de la taille d'une ligne de coffre (9 * nombre de lignes)
inventoriesName:
  createTeam: "§5§lCréation de Team"
  admin: "§5§lMenu principal"
  manage: "§5§lGérer la team"
  member: "§5§lOptions de la team"
  teamMembers: "§5§lMembres"
  teamAlliances: "§5§lAlliances"
  editMembers: "§5§lGestion des membres"
  editAlliances: "§5§lGestion des alliances"
  upgradeTotalMembers: "§5§lPlaces disponibles"
  confirmInventory: "§5§lConfirmation"
  permissions: "§5§lPermissions"
  upgradeStorageAmount: "§5§lAméliorations du stockage"
  storageDirectory: "§5§lStockages disponibles"
  storages:
    storageOne: "§5§lStockage 1"
    storageTwo: "§5§lStockage 2"
    storageThree: "§5§lStockage 3"
    storageFour: "§5§lStockage 4"
    storageFive: "§5§lStockage 5"


# Nombre de slots dans chaque inventaires. A modifier en fonction de la taille d'une ligne de coffre (9 * nombre de lignes) 
inventoriesSlots:
  createTeam: 27
  admin: 27
  manage: 45
  member: 45
  teamMembers: 27
  teamAlliances: 27
  editMembers: 36
  editAlliances: 36
  upgradeTotalMembers: 27
  confirmInventory: 27
  permissions: 45
  upgradeStorageAmount: 27
  storageDirectory: 27
  storage: 54


ranks:
  owner:
    id: 0
    name: "Chef"
    color: "§c"
  co_owner:
    id: 1
    name: "Chef adjoint"
    color: "§d"
  moderator:
    id: 2
    name: "Ainé"
    color: "§6"
  member:
    id: 3
    name: "Membre"
    color: "§e"
  new_member:
    id: 4
    name: "Nouveau Membre"
    color: "§7"
  # coop:
  #   id: 6
  #   name: "Coop"
  #   color: "§8"
  # alliance:
  #   id: 7
  #   name: "Alliance"
  #   color: "§a"


# Description des items en fonction des grades, dans le menu d'éition des membres
editMembersLores:
  - "§7§oClique gauche pour promouvoir"
  - "§7§oClique droit pour rétrograder"


inventories:
  createTeam:
    itemName: "§5§nCréer une team"
    itemType: LIME_BANNER
    slot: 13
    lore: 
      - "§aPrix : 100 000€"

  admin:
    manage:
      itemName: "§5§nMenu de gestion"
      itemType: WRITABLE_BOOK
      slot: 12
      lore:
        - "§aGére les différents"
        - "§aparamètres de la team"
    member:
      itemName: "§5§nMenu de la team"
      itemType: PLAYER_HEAD
      slot: 14
      lore:
        - "§aVisualise les options"
        - "§ade la team"
    close:
      itemName: "§c§oFermer"
      itemType: BARRIER
      slot: 26


  manage:
    editMembers:
      itemName: "§5§nGestion des membres"
      itemType: WRITABLE_BOOK
      slot: 9
      rank: 2
      lore:
        - "§aGérer les membres"
        - "§ade la team"
    editAlliances:
      itemName: "§5§nGestion des alliances"
      itemType: FEATHER
      slot: 18
      rank: 2
      lore:
        - "§aGérer les alliances"
        - "§ade la team"
    setTeamHome:
      itemName: "§5§nCréer un home"
      itemType: GREEN_BED
      slot: 11
      rank: 2
      lore:
        - "§aCréer le home de team"
    removeTeamHome:
      itemName: "§5§nRetirer le home"
      itemType: RED_BED
      slot: 20
      rank: 2
      lore:
        - "§aRetirer le home de team"
    buyTeamBank:
      itemName: "§5§nOuvrir le compte"
      itemType: GOLD_BLOCK
      slot: 13
      rank: 2
      lore:
        - "§aCréer le compte banquaire"
        - "§ade la team"
        - "§b§oPrix : 1 000 000€"
    upgradeTotalMembers:
      itemName: "§5§nAjouter des places"
      itemType: TOTEM_OF_UNDYING
      slot: 15
      rank: 2
      lore:
        - "§aAméliorer le nombre de"
        - "§amembres maximum dans la team"
    upgradeStorageAmount:
      itemName: "§5§nAjouter du stockage"
      itemType: CHEST
      slot: 24
      rank: 2
      lore:
        - "§aAméliorer le nombre de"
        - "§astockage maximum dans la team"
    editName:
      itemName: "§5§nModifier le nom"
      itemType: PAPER
      slot: 17
      rank: 2
      lore:
        - "§aModifier le nom de la team"
        - "§b§oPrix : 5 000€"
    editPrefix:
      itemName: "§5§nModifier le préfixe"
      itemType: NAME_TAG
      slot: 26
      rank: 2
      lore:
        - "§aModifier le préfixe de la team"
        - "§aqui s'affiche dans le tchat"
        - "§b§oPrix : 5 000€"
        - ""
        - "§7§oVous pouvez prévisualiser"
        - "§7§ole préfixe avec la commande :"
        - "§7§o/stelyteam visual <texte>"
    editPermissions:
      itemName: "§5§nPermissions"
      itemType: RED_BANNER
      slot: 22
      rank: 2
      lore:
        - "§aGérer les permissions"
        - "§ade la team"
    removeTeam:
      itemName: "§c§nSupprimer la team"
      itemType: COMPOSTER
      slot: 40
      rank: 0
    close:
      itemName: "§c§oFermer"
      itemType: BARRIER
      slot: 44


  member:
    teamInfos:
      itemName: "§5§nInformations"
      itemType: BOOK
      slot: 11
      rank: -1
      lore:
        - "§aGérant de la team : §e%OWNER%"
        - "§aNom : §e%NAME%"
        - "§aPréfixe : §r%PREFIX%"
        - "§aNombre de membre : §e%MEMBER_COUNT% sur %MAX_MEMBERS%"        
        - "§aDate de la création : §e%DATE%"    
        - ""        
        - "§aTon grade : §r%RANK%"
    seeTeamMembers:
      itemName: "§5§nMembres"
      itemType: TOTEM_OF_UNDYING
      slot: 20
      rank: 5
      lore:
        - "§aClique pour voir les"  
        - "§amembres de la team"      
    seeTeamAlliances:
      itemName: "§5§nAlliances"
      itemType: FEATHER
      slot: 29
      rank: 5
      lore:
        - "§aClique pour voir les"  
        - "§aalliances de la team"        
    seeTeamBank:
      itemName: "§5§nArgent de la team"
      itemType: EMERALD
      slot: 13
      rank: 4
      lore:
        - "§aCompte : §6%TEAM_MONEY%€"
        - "§aPlafond du compte : §6%MAX_MONEY%€"
    addTeamMoney:
      itemName: "§5§nAjout d'argent"
      itemType: GOLD_NUGGET
      slot: 22
      rank: 4
      lore:
        - "§aAjouter de l'argent dans"
        - "§ale compte de la team"
    withdrawTeamMoney:
      itemName: "§5§nRetrait d'argent"
      itemType: PAPER
      slot: 31
      rank: 4
      lore:
        - "§aRetirer de l'argent dans"
        - "§ale compte de la team"
    storageDirectory:
      itemName: "§5§nStockage"
      itemType: CHEST
      slot: 15
      rank: 4
      lore:
        - "§aClique pour voir le"
        - "§astockage de la team"
    leaveTeam:
      itemName: "§c§nQuitter la team"
      itemType: DARK_OAK_DOOR
      slot: 33
      rank: -1
    close:
      itemName: "§c§oFermer"
      itemType: BARRIER
      slot: 44


  upgradeTotalMembers:
    levelOne:
      itemName: "§5§n11 places"
      itemType: IRON_INGOT
      slot: 11
      level: 1
      lore:
        - "§b§oPrix : 25 000€"
    levelTwo:
      itemName: "§5§n12 places"
      itemType: GOLD_INGOT
      slot: 12
      level: 2
      lore:
        - "§b§oPrix : 50 000€"
    levelThree:
      itemName: "§5§n13 places"
      itemType: DIAMOND
      slot: 13
      level: 3
      lore:
        - "§b§oPrix : 100 000€"
    levelFour:
      itemName: "§5§n14 places"
      itemType: EMERALD
      slot: 14
      level: 4
      lore:
        - "§b§oPrix : 150 000€"
    levelFive:
      itemName: "§5§n15 places"
      itemType: NETHERITE_INGOT
      slot: 15
      level: 5
      lore:
        - "§b§oPrix : 250 000€"
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 26


  upgradeStorageAmount:
    storageOne:
      itemName: "§5§n1 stockage"
      itemType: BARREL
      slot: 11
      level: 1
      lore:
        - "§b§oPrix : 10 000€"
    storageTwo:
      itemName: "§5§n2 stockages"
      itemType: BARREL
      slot: 12
      level: 2
      lore:
        - "§b§oPrix : 25 000€"
    storageThree:
      itemName: "§5§n3 stockages"
      itemType: BARREL
      slot: 13
      level: 3
      lore:
        - "§b§oPrix : 50 000€"
    storageFour:
      itemName: "§5§n4 stockages"
      itemType: BARREL
      slot: 14
      level: 4
      lore:
        - "§b§oPrix : 80 000€"
    storageFive:
      itemName: "§5§n5 stockages"
      itemType: BARREL
      slot: 15
      level: 5
      lore:
        - "§b§oPrix : 100 000€"
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 26


  confirmInventory:
    confirm:
      itemName: "§a§nConfirmer"
      itemType: LIME_STAINED_GLASS_PANE
      slots: [13]
    cancel:
      itemName: "§c§lAnnuler"
      itemType: RED_STAINED_GLASS_PANE
      slots: [9, 10, 11, 12, 14, 15, 16, 17]


  teamMembers:
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 26


  teamAlliances:
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 26


  editMembers:
    addMember:
      itemName: "§5§nAjouter un membre"
      itemType: GOLD_INGOT
      slot: 27
      rank: 2
      lore:
        - "§aAjouter un membre à la team"
    removeMember:
      itemName: "§5§nRetirer un membre"
      itemType: RAW_GOLD
      slot: 28
      rank: 2
      lore:
        - "§aRetirer un membre de la team"
    editOwner:
      itemName: "§5§nChanger de créateur"
      itemType: LECTERN
      slot: 31
      rank: 0
      lore:
        - "§aModifier le créateur"
        - "§ade la team"
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 35


  editAlliances:
    addAlliance:
      itemName: "§5§nAjouter une alliance"
      itemType: PRISMARINE_SHARD
      slot: 27
      rank: 1
      lore:
        - "§aAjouter une alliance à la team"
    removeAlliance:
      itemName: "§5§nRetirer une alliance"
      itemType: PRISMARINE_CRYSTALS
      slot: 28
      rank: 1
      lore:
        - "§aRetirer une alliance de la team"
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 35


  permissions:
    addTeamMoney:
      itemName: "§5§nAjouter de l'argent"
      itemType: GOLD_NUGGET
      slot: 10
      rankPath: member.addTeamMoney
      lore:
        - "§aAjouter de l'argent dans la team"
    withdrawTeamMoney:
      itemName: "§5§nRetirer de l'argent"
      itemType: PAPER
      slot: 11
      rankPath: member.withdrawTeamMoney
      lore:
        - "§aRetirer de l'argent de la team"
    seeTeamBank:
      itemName: "§5§nVoir l'argent"
      itemType: EMERALD
      slot: 12
      rankPath: member.seeTeamBank
      lore:
        - "§aVoir l'argent de la team"
    buyTeamBank:
      itemName: "§5§nAchat du compte"
      itemType: GOLD_BLOCK
      slot: 13
      rankPath: manage.buyTeamBank
      lore:
        - "§aAchat du compte de team"
    addMember:
      itemName: "§5§nAjouter un membre"
      itemType: GOLD_INGOT
      slot: 14
      rankPath: editMembers.addMember
      lore:
        - "§aAjouter un membre à la team"
    removeMember:
      itemName: "§5§nRetirer un membre"
      itemType: RAW_GOLD
      slot: 15
      rankPath: editMembers.removeMember
      lore:
        - "§aRetirer un membre de la team"
    seeTeamMembers:
      itemName: "§5§nVoir les membres"
      itemType: TOTEM_OF_UNDYING
      slot: 16
      rankPath: member.seeTeamMembers
      lore:
        - "§aVoir les membres de la team"
    upgradeTotalMembers:
      itemName: "§5§nAugmenter les places disponibles"
      itemType: EXPERIENCE_BOTTLE
      slot: 19
      rankPath: manage.upgradeTotalMembers
      lore:
        - "§aAugmenter le nombre de places"
        - "§adisponible dans la team"
    manageMembers:
      itemName: "§5§nGestion des membres"
      itemType: WRITABLE_BOOK
      slot: 20
      rankPath: manage.editMembers
      lore:
        - "§aGérer les membres de la team"
    editName:
      itemName: "§5§nModifier le nom"
      itemType: PAPER
      slot: 21
      rankPath: manage.editName
      lore:
        - "§aModifier le nom de la team"
    editPrefix:
      itemName: "§5§nModifier le préfixe"
      itemType: NAME_TAG
      slot: 22
      rankPath: manage.editPrefix
      lore:
        - "§aModifier le préfixe de la team"
    setTeamHome:
      itemName: "§5§nCréer le home"
      itemType: GREEN_BED
      slot: 23
      rankPath: manage.setTeamHome
      lore:
        - "§aDéfinir le home de la team"
    removeTeamHome:
      itemName: "§5§nSupprimer la home"
      itemType: RED_BED
      slot: 24
      rankPath: manage.removeTeamHome
      lore:
        - "§aRetirer le home de la team"
    editPermissions:
      itemName: "§5§nModifier les permissions"
      itemType: REDSTONE
      slot: 25
      rankPath: manage.editPermissions
      lore:
        - "§aModifier les permissions de la team"
    storageDirectory:
      itemName: "§5§nAccès aux stockages"
      itemType: BARREL
      slot: 32
      rankPath: member.storageDirectory
      lore:
        - "§aPermet d'avoir accès aux"
        - "§astockages de la team"
    upgradeStorageAmount:
      itemName: "§5§nAugmenter les stockages disponibles"
      itemType: COMPOSTER
      slot: 30
      rankPath: manage.upgradeStorageAmount
      lore:
        - "§aAugmenter le nombre de stockages"
        - "§adisponible dans la team"
    addAlliance:
      itemName: "§5§nAjouter une alliance"
      itemType: PRISMARINE_SHARD
      slot: 31
      rankPath: editAlliances.addAlliance
      lore:
        - "§aAjouter une alliance à la team"
    removeAlliance:
      itemName: "§5§nRetirer une alliance"
      itemType: PRISMARINE_CRYSTALS
      slot: 32
      rankPath: editAlliances.removeAlliance
      lore:
        - "§aRetirer une alliance de la team"
    seeTeamAlliances:
      itemName: "§5§nVoir les alliances"
      itemType: ENDER_EYE
      slot: 33
      rankPath: member.seeTeamAlliances
      lore:
        - "§aVoir les alliances de la team"
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 44


  storage:
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 53


  storageDirectory: 
    storageOne:
      itemName: inventoriesName.storages.storageOne
      itemType: CHEST
      level: 1
      storageId: 1
      slot: 11
    storageTwo:
      itemName: inventoriesName.storages.storageTwo
      itemType: CHEST
      level: 2
      storageId: 2
      slot: 12
    storageThree:
      itemName: inventoriesName.storages.storageThree
      itemType: CHEST
      level: 3
      storageId: 3
      slot: 13
    storageFour:
      itemName: inventoriesName.storages.storageFour
      itemType: CHEST
      level: 4
      storageId: 4
      slot: 14
    storageFive:
      itemName: inventoriesName.storages.storageFive
      itemType: CHEST
      level: 5
      storageId: 5
      slot: 15
    close:
      itemName: "§c§oRetour"
      itemType: BARRIER
      slot: 26
