# Connection à la base de donnée
sql:
  host: "localhost"
  database: "bungeecord_StelyTeam"
  user: "username"
  password: "password"
  port: 3306


# Timeout des conversations (message demandant une information aux joueurs lors de la création de team par exemple)
conversationTimeout: 60

# Mots permettant d'annuler une conversation (message demandant une information aux joueurs lors de la création de team par exemple)
conversationCancelWords:
  - "cancel"
  - "annuler"
  - "stop"
  - "quit"

# Nombre maximum de caracteres dans les noms de team (les couleurs ne sont pas prises en compte dans la limite)
teamNameMaxLength: 12
teamPrefixMaxLength: 12

# Argent maximal d'une team
teamMaxMoney: 10000000.0

# Nombre de membres maximum dans une team
teamMaxMembers: 10

# Prix des différentes actions
prices:
  createTeam: 100000.0
  editTeamId: 5000.0
  editTeamPrefix: 5000.0
  buyTeamBank: 1000000.0
  upgrade:
    teamPlaces:
      level1: 2500000.0
      level2: 5000000.0
      level3: 10000000.0
      level4: 15000000.0
      level5: 25000000.0
    teamStorages:
      level1: 2500000.0
      level2: 5000000.0
      level3: 10000000.0
      level4: 15000000.0
      level5: 25000000.0


# Item à la place des cases vide
emptyCase: BLACK_STAINED_GLASS_PANE

# Item en cas de permission insuffisante
noPermission:
  itemName: "§cPermission insuffisante"
  itemType: RED_STAINED_GLASS_PANE
  lore: 
    - "§cPermission insuffisante"


# Item si le compte de la team n'a pas encore été débloquée
teamBankNotUnlock:
  itemName: "§cCompte non débloqué"
  itemType: EMERALD
  lore: 
    - "§cDébloquer le compte de"
    - "§cla team pour pouvoir"
    - "§cy avoir accès"

# Item si l'un des stockage de la team n'a pas encore été débloqué
storageNotUnlock:
  itemName: "§cStockage non débloqué"
  itemType: ENDER_CHEST
  lore: 
    - "§cDébloquer ce stockage"
    - "§cpour pouvoir y avoir"
    - "§caccès"



# Préfixe à gauche du rang, affiché dans le menu de la gestion des membres de la team et dans la liste des membres
prefixRankLore: "§r§5> "


# Titre des menus et leur nombre de slots
# Le nombre de slots peut être augmenté en fonction du tombre d'item dans le menu *
# * Respecter le nombre de slots en fonction de la taille d'une ligne de coffre (9 * nombre de lignes)
inventoriesName:
  createTeam: "§5§lCréer une team"
  admin: "§5§lAdministrateur"
  manage: "§5§lGérer la team"
  member: "§5§lMenu Membre"
  teamMembers: "§5§lMembres"
  editMembers: "§5§lGestion des membres"
  upgradeTotalMembers: "§5§lPlaces disponibles"
  confirmInventory: "§5§lConfirmation"
  permissions: "§5§lPermissions"
  upgradeStorageAmount: "§5§lAméliorations du stockage"
  storageDirectory: "§5§lStockages disponibles"
  storage: "§5§lStockage"
  storageOne: "§5§lStockage 1"
  storageTwo: "§5§lStockage 2"
  storageThree: "§5§lStockage 3"
  storageFour: "§5§lStockage 4"
  storageFive: "§5§lStockage 5"


# Nombre de slots dans chaque inventaires. A modifier en fonction de la taille d'une ligne de coffre (9 * nombre de lignes) 
inventoriesSlots:
  createTeam: 27
  admin: 27
  manage: 36
  member: 45
  teamMembers: 27
  editMembers: 36
  upgradeTotalMembers: 27
  confirmInventory: 27
  permissions: 45
  upgradeStorageAmount: 27
  storageDirectory: 27
  storage: 54


ranks:
  owner:
    id: 0
    name: "Gérant"
    color: "§5"
  co_owner:
    id: 1
    name: "Co-Gérant"
    color: "§d"
  admin:
    id: 2
    name: "Admin"
    color: "§9"
  moderator:
    id: 3
    name: "Modérateur"
    color: "§3"
  member:
    id: 4
    name: "Membre"
    color: "§2"
  new_member:
    id: 5
    name: "Nouveau Membre"
    color: "§e"
  # coop:
  #   id: 6
  #   name: "Coop"
  #   color: "§8"
  # alliance:
  #   id: 7
  #   name: "Alliance"
  #   color: "§a"


# Description des items en fonction des grades, dans le menu d'éition des membres
editMembersLores:
  - "Clique gauche pour promouvoir"
  - "Clique droit pour rétrograder"


inventories:
  createTeam:
    itemName: "§5§lCréer une team"
    itemType: RED_BANNER
    slot: 13
    lore: 
      - "§aPrix : 100,000€"


  admin:
    manage:
      itemName: "§5§lMenu Gestion"
      itemType: BOOK
      slot: 12
      lore:
        - "§aGérer les différents"
        - "§aparamètres de la team"
    member:
      itemName: "§5§lMenu Membre"
      itemType: PAPER
      slot: 14
      lore:
        - "§aMenu du membre de"
        - "§ala team"
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 26


  manage:
    editMembers:
      itemName: "§5§lGestion des membres"
      itemType: WRITABLE_BOOK
      slot: 11
      rank: 2
      lore:
        - "§aGérer les membres de la"
        - "§ateam"
    setTeamHome:
      itemName: "§5§lCréer un home"
      itemType: GREEN_BED
      slot: 12
      rank: 2
      lore:
        - "§aCréer le home de team"
    removeTeamHome:
      itemName: "§5§lRetirer le home"
      itemType: RED_BED
      slot: 13
      rank: 2
      lore:
        - "§aRetirer le home de team"
    buyTeamBank:
      itemName: "§5§lOuvrir le compte"
      itemType: GOLD_BLOCK
      slot: 14
      rank: 2
      lore:
        - "§aCréer le compte banquaire"
        - "§ade la team"
        - "§aPrix : 1,000,000€"
    upgradeTotalMembers:
      itemName: "§5§lAjouter des places"
      itemType: TOTEM_OF_UNDYING
      slot: 15
      rank: 2
      lore:
        - "§aAméliorer le nombre de"
        - "§amembres dans la team"
    upgradeStorages:
      itemName: "§5§lAjouter des stockages"
      itemType: CHEST
      slot: 20
      rank: 2
      lore:
        - "§aAméliorer le nombre de"
        - "§astockages dans la team"
    editName:
      itemName: "§5§lModifier le nom"
      itemType: PAPER
      slot: 21
      rank: 2
      lore:
        - "§aModifier le nom unique"
        - "§ade la team"
        - "§aPrix : 5,000€"
    editPrefix:
      itemName: "§5§lModifier le préfixe"
      itemType: NAME_TAG
      slot: 22
      rank: 2
      lore:
        - "§aModifier le nom de la"
        - "§ateam qui s'affiche dans"
        - "§ale tchat"
        - "§aPrix : 5,000€"
        - ""
        - "§cAssurez-vous d'avoir"
        - "§cessayé le préfixe avant,"
        - "§cavec /stelyteam visual"
    removeTeam:
      itemName: "§5§lSupprimer la team"
      itemType: COMPOSTER
      slot: 24
      rank: 0
      lore:
        - "§aSupprimer la team"
    editPermissions:
      itemName: "§5§lPermissions"
      itemType: RED_BANNER
      slot: 23
      rank: 2
      lore:
        - "§aGérer les permissions"
        - "§ade la team"
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 35


  member:
    teamInfos:
      itemName: "§5§lInfos"
      itemType: BOOK
      slot: 13
      rank: -1
      lore:
        - "§aNom : §r%NAME%"
        - "§aPréfixe : §r%PREFIX%"
        - "§aGérant : §r%OWNER%"
        - "§aGrade : §r%RANK%"
        - "§aArrivé : §r%DATE%"
        - "§aMembres : §r%MEMBER_COUNT% / %MAX_MEMBERS%"
    seeTeamMembers:
      itemName: "§5§lMembres"
      itemType: TOTEM_OF_UNDYING
      slot: 20
      rank: 5
    seeTeamBank:
      itemName: "§5§lArgent de la team"
      itemType: EMERALD
      slot: 21
      rank: 4
      lore:
        - "§aMontant : %TEAM_MONEY%€"
        - "§aMax : %MAX_MONEY%€"
    addTeamMoney:
      itemName: "§5§lAjout d'argent"
      itemType: GOLD_NUGGET
      slot: 22
      rank: 4
      lore:
        - "§aAjouter de l'argent"
        - "§adans la team"
    withdrawTeamMoney:
      itemName: "§5§lRetrait d'argent"
      itemType: PAPER
      slot: 23
      rank: 4
      lore:
        - "§aRetirer de l'argent"
        - "§ade la team"
    leaveTeam:
      itemName: "§5§lQuitter la team"
      itemType: DARK_OAK_DOOR
      slot: 24
      rank: -1
    storageDirectory:
      itemName: "§5§lStockages"
      itemType: CHEST
      slot: 31
      rank: 4
      lore:
        - "§aStockages de la team"
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 44


  upgradeTotalMembers:
    levelOne:
      itemName: "§5§l11 places"
      itemType: IRON_INGOT
      slot: 11
      level: 1
      lore:
        - "§aPrix : 2,500,000€"
    levelTwo:
      itemName: "§5§l12 places"
      itemType: GOLD_INGOT
      slot: 12
      level: 2
      lore:
        - "§aPrix : 5,000,000€"
    levelThree:
      itemName: "§5§l13 places"
      itemType: DIAMOND
      slot: 13
      level: 3
      lore:
        - "§aPrix : 10,000,000€"
    levelFour:
      itemName: "§5§l14 places"
      itemType: EMERALD
      slot: 14
      level: 4
      lore:
        - "§aPrix : 15,000,000€"
    levelFive:
      itemName: "§5§l15 places"
      itemType: NETHERITE_INGOT
      slot: 15
      level: 5
      lore:
        - "§aPrix : 25,000,000€"
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 26


  upgradeStorageAmount:
    storageOne:
      itemName: "§5§l1 stockage"
      itemType: BARREL
      slot: 11
      level: 1
      lore:
        - "§aPrix : 2,500,000€"
    storageTwo:
      itemName: "§5§l2 stockages"
      itemType: BARREL
      slot: 12
      level: 2
      lore:
        - "§aPrix : 5,000,000€"
    storageThree:
      itemName: "§5§l3 stockages"
      itemType: BARREL
      slot: 13
      level: 3
      lore:
        - "§aPrix : 10,000,000€"
    storageFour:
      itemName: "§5§l4 stockages"
      itemType: BARREL
      slot: 14
      level: 4
      lore:
        - "§aPrix : 15,000,000€"
    storageFive:
      itemName: "§5§l5 stockages"
      itemType: BARREL
      slot: 15
      level: 5
      lore:
        - "§aPrix : 25,000,000€"
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 26


  confirmInventory:
    confirm:
      itemName: "§a§lConfirmer"
      itemType: LIME_STAINED_GLASS_PANE
      slots: [13]
    cancel:
      itemName: "§c§lAnnuler"
      itemType: RED_STAINED_GLASS_PANE
      slots: [9, 10, 11, 12, 14, 15, 16, 17]


  teamMembers:
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 26


  editMembers:
    addMember:
      itemName: "§5§lAjouter un membre"
      itemType: GOLD_INGOT
      slot: 27
      rank: 2
      lore:
        - "§aAjouter un membre à la team"
    removeMember:
      itemName: "§5§lRetirer un membre"
      itemType: RAW_GOLD
      slot: 28
      rank: 2
      lore:
        - "§aRetirer un membre de la team"
    editOwner:
      itemName: "§5§lChanger de créateur"
      itemType: DIAMOND
      slot: 31
      rank: 0
      lore:
        - "§aModifier le créateur"
        - "§ade la team"
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 35


  permissions:
    addTeamMoney:
      itemName: "§5§lAjouter de l'argent"
      itemType: GOLD_NUGGET
      slot: 10
      rankPath: "member.addTeamMoney"
      lore:
        - "§aAjouter de l'argent dans la team"
    withdrawTeamMoney:
      itemName: "§5§lRetirer de l'argent"
      itemType: PAPER
      slot: 11
      rankPath: "member.withdrawTeamMoney"
      lore:
        - "§aRetirer de l'argent de la team"
    seeTeamBank:
      itemName: "§5§lVoir l'argent"
      itemType: EMERALD
      slot: 12
      rankPath: "member.seeTeamBank"
      lore:
        - "§aVoir l'argent de la team"
    buyTeamBank:
      itemName: "§5§lAchat du compte"
      itemType: GOLD_BLOCK
      slot: 13
      rankPath: "manage.buyTeamBank"
      lore:
        - "§aAchat du compte de team"
    addMember:
      itemName: "§5§lAjouter un membre"
      itemType: GOLD_INGOT
      slot: 14
      rankPath: "editMembers.addMember"
      lore:
        - "§aAjouter un membre à la team"
    removeMember:
      itemName: "§5§lRetirer un membre"
      itemType: RAW_GOLD
      slot: 15
      rankPath: "editMembers.removeMember"
      lore:
        - "§aRetirer un membre de la team"
    seeTeamMembers:
      itemName: "§5§lVoir les membres"
      itemType: TOTEM_OF_UNDYING
      slot: 16
      rankPath: "member.seeTeamMembers"
      lore:
        - "§aVoir les membres de la team"
    upgradeTotalMembers:
      itemName: "§5§lAugmenter les places disponibles"
      itemType: EXPERIENCE_BOTTLE
      slot: 19
      rankPath: "manage.upgradeTotalMembers"
      lore:
        - "§aAugmenter le nombre de places"
        - "§adisponible dans la team"
    manageMembers:
      itemName: "§5§lGestion des membres"
      itemType: WRITABLE_BOOK
      slot: 20
      rankPath: "manage.editMembers"
      lore:
        - "§aGérer les membres de la team"
    editName:
      itemName: "§5§lModifier le nom"
      itemType: PAPER
      slot: 21
      rankPath: "manage.editName"
      lore:
        - "§aModifier le nom de la team"
    editPrefix:
      itemName: "§5§lModifier le préfixe"
      itemType: NAME_TAG
      slot: 22
      rankPath: "manage.editPrefix"
      lore:
        - "§aModifier le préfixe de la team"
    setTeamHome:
      itemName: "§5§lCréer le home"
      itemType: GREEN_BED
      slot: 23
      rankPath: "manage.setTeamHome"
      lore:
        - "§aDéfinir le home de la team"
    removeTeamHome:
      itemName: "§5§lSupprimer la home"
      itemType: RED_BED
      slot: 24
      rankPath: "manage.removeTeamHome"
      lore:
        - "§aRetirer le home de la team"
    editPermissions:
      itemName: "§5§lModifier les permissions"
      itemType: REDSTONE
      slot: 25
      rankPath: "manage.editPermissions"
      lore:
        - "§aModifier les permissions de la team"
    storageDirectory:
      itemName: "§5§lAccès aux stockages"
      itemType: BARREL
      slot: 31
      rankPath: "member.storageDirectory"
      lore:
        - "§aPermet d'avoir accès aux"
        - "§astockages de la team"
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 35


  storage:
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 53


  storageDirectory: 
    storageOne:
      itemName: "§5§lStockage 1"
      itemType: CHEST
      level: 1
      storageId: "storage_1"
      slot: 11
    storageTwo:
      itemName: "§5§lStockage 2"
      itemType: CHEST
      level: 2
      storageId: "storage_2"
      slot: 12
    storageThree:
      itemName: "§5§lStockage 3"
      itemType: CHEST
      level: 3
      storageId: "storage_3"
      slot: 13
    storageFour:
      itemName: "§5§lStockage 4"
      itemType: CHEST
      level: 4
      storageId: "storage_4"
      slot: 14
    storageFive:
      itemName: "§5§lStockage 5"
      itemType: CHEST
      level: 5
      storageId: "storage_5"
      slot: 15
    close:
      itemName: "§5§lFermer"
      itemType: BARRIER
      slot: 26
