name: StelyTeam
author: Army_
version: "${project.version}"
main: fr.army.stelyteam.StelyTeamPlugin
api-version: "1.16"
commands:
  stelyteam:
    description: "StelyTeam"
    usage: "/stelyteam <option>"