package fr.army.stelyteam.config.message;

public enum Placeholders {

    PLAYER_NAME,
    PLAYER_DISPLAY_NAME,
    TEAM_NAME,
    TEAM_PREFIX,
    TEAM_DESCRIPTION,
    TEAM_OWNER_NAME,
    TEAM_OWNER_DISPLAY_NAME,
    TEAM_UNLOCKED_BANK,
    TEAM_MEMBER_COUNT,
    TEAM_MEMBERS,
    TEAM_CREATION_DATE,
    TEAM_MONEY,
    TEAM_OWNER_SKULL_TEXTURE,

    MEMBER_RANK,

    CONFIG_MAX_MEMBERS_COUNT,
    CONFIG_MAX_MONEY_LIMIT,

    CURRENT_PAGE,
    MAX_PAGE,
    ;
}
